In [1]:
from pathlib import Path
import sys
import pandas as pd


SRC_DIR = Path().resolve().parent / "src"
sys.path.append("../src")
sys.path.append("../src/reading_data")

from reading_data import df_municipios, df_policia, df_violencia_mortes

Reading parquet: C:\Users\danie\OneDrive\Área de Trabalho\graduacao\data-visualization\T3\data\raw\data_municipios.parquet
Reading parquet: C:\Users\danie\OneDrive\Área de Trabalho\graduacao\data-visualization\T3\data\raw\data_violencia_mortes.parquet
Reading parquet: C:\Users\danie\OneDrive\Área de Trabalho\graduacao\data-visualization\T3\data\raw\data_policia.parquet

In [33]:
df_municipios = pd.read_parquet('../data/raw/data_municipios.parquet')

In [2]:
df_municipios.head(5)

,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,...,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf,nome_uf,nome_regiao,amazonia_legal,centroide
0,1100338,110033,434,47,44516,Nova Mamoré,0,1100106,11004,Madeira-Mamoré,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-64.6295025002404 -10.3822863210755)
1,1100205,110020,35,3,30719,Porto Velho,1,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-64.3041357999869 -9.15394033687075)
2,1101104,110110,493,683,46851,Itapuã do Oeste,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-63.044960463046 -9.17019402601564)
3,1100809,110080,477,681,46961,Candeias do Jamari,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-63.3254198532114 -8.88702392955617)
4,1100940,110094,680,8,56652,Cujubim,0,1100023,11001,Vale do Jamari,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-62.5652673033848 -9.1709863446154)

In [4]:
display(df_policia.head(5))
print("columns")
print(df_policia.columns)

,DEPARTAMENTO_CIRCUNSCRICAO,SECCIONAL_CIRCUNSCRICAO,MUNICIPIO_CIRCUNSCRICAO,DP_CIRCUNSCRICAO,COORPORAÇÃO,SITUAÇÃO,ID_DELEGACIA,MÊS ESTATISTICA,ANO ESTATISTICA,DATAHORA_REGISTRO_BO,...,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,TIPO_PESSOA,SEXO_PESSOA,IDADE_PESSOA,DATA_NASCIMENTO_PESSOA,COR_PELE,PROFISSAO,NATUREZA_APURADA
0,DECAP,DEL.SEC.2º SUL,S.PAULO,95º D.P. HELIÓPOLIS,PC,Folga,200100,1,2013,None,...,NÃO INFORMADO,"-46,60207908",0,Adolescente infrator,Masculino,17,23/01/1995,Parda,None,MORTE DECORRENTE DE INTERVENÇÃO POLICIAL
1,DECAP,DEL.SEC.3º OESTE,S.PAULO,14º D.P. PINHEIROS,PC,Folga,200100,1,2013,None,...,450,"-46,69034708",0,Autor/Vítima,Masculino,34,29/11/1978,Branca,VIGILANTE,MORTE DECORRENTE DE INTERVENÇÃO POLICIAL
2,DEMACRO,DEL.SEC.OSASCO,OSASCO,06º D.P. OSASCO,PC,Folga,200100,1,2013,None,...,169,"-46,78006935",0,Autor/Vítima,Masculino,39,23/05/1973,Branca,MARCENEIRO(A),MORTE DECORRENTE DE INTERVENÇÃO POLICIAL
3,DECAP,DEL.SEC.2º SUL,S.PAULO,27º DP DR. IGNÁCIO FRANCISCO,PM,Folga,200100,1,2013,24/01/2013,...,5599,"-23,6262914","-46,64895387",Vítima,Masculino,None,None,Branca,None,MORTE DECORRENTE DE INTERVENÇÃO POLICIAL
4,DECAP,DEL.SEC.3º OESTE,S.PAULO,33º D.P. PIRITUBA,PM,Folga,200100,1,2013,15/01/2013,...,3015,"-23,49108279","-46,75077863",Autor/Vítima,Masculino,23,21/09/1989,Parda,None,MORTE DECORRENTE DE INTERVENÇÃO POLICIAL

columns
Index(['DEPARTAMENTO_CIRCUNSCRICAO', 'SECCIONAL_CIRCUNSCRICAO',
       'MUNICIPIO_CIRCUNSCRICAO', 'DP_CIRCUNSCRICAO ', 'COORPORAÇÃO',
       'SITUAÇÃO', 'ID_DELEGACIA', 'MÊS ESTATISTICA', 'ANO ESTATISTICA',
       'DATAHORA_REGISTRO_BO', 'NUM_BO', 'ANO_BO', 'MUNICIPIO_ELABORACAO',
       'DP_ELABORACAO', 'SEC_ELABORACAO', 'DEP_ELABORACAO', 'DATA_FATO',
       'HORA_FATO', 'DESC_TIPOLOCAL', 'LOGRADOURO', 'NUMERO_LOGRADOURO',
       'LATITUDE', 'LONGITUDE', 'TIPO_PESSOA', 'SEXO_PESSOA', 'IDADE_PESSOA',
       'DATA_NASCIMENTO_PESSOA', 'COR_PELE', 'PROFISSAO', 'NATUREZA_APURADA'],
      dtype='object')

In [26]:
df_violencia_mortes = pd.read_csv("../data/raw/data_violencia_mortes.csv.gz")
print(30*"=")
print("df_violencia mortes")
display(df_violencia_mortes)
print("columns")
print(df_violencia_mortes.columns)

colunas_importantes = [
    "ano",
    "sigla_uf",
    "id_municipio",
    "grupo",
]

# Selecionando mortes por violência policial
df_mortes_interv_policiais = df_violencia_mortes.filter(like='mortes_intervencao_policial', axis=1)
# Selecionando colunas com informações
df_informacoes = df_violencia_mortes[colunas_importantes]
# Juntando os dois dataframes
df_mortes_interv_policiais = pd.concat([df_informacoes, df_mortes_interv_policiais], axis=1)

==============================
df_violencia mortes

,ano,sigla_uf,id_municipio,grupo,quantidade_homicidio_doloso,quantidade_latrocinio,quantidade_lesao_corporal_morte,quantidade_mortes_policiais_confronto,quantidade_mortes_intervencao_policial,quantidade_mortes_intervencao_policial_civil_em_servico,...,proporcao_mortes_intenvencao_policial_x_mortes_violentas_intencionais,quantidade_posse_ilegal_arma_de_fogo,quantidade_porte_ilegal_arma_de_fogo,quantidade_posse_ilegal_porte_ilegal_arma_de_fogo,quantidade_trafico_entorpecente,quantidade_posse_uso_entorpecente,quantidade_morte_policiais_civis_confronto_em_servico,quantidade_morte_policiais_militares_confronto_em_servico,quantidade_morte_policiais_civis_fora_de_servico,quantidade_morte_policiais_militares_fora_de_servico
0,2016,AL,2704302,Grupo 1,449,21,2.0,5.0,59.0,0.0,...,11.0,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,2.0
1,2016,CE,2304400,Grupo 1,965,27,15.0,8.0,39.0,1.0,...,3.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,2.0,5.0
2,2016,ES,3205309,Grupo 1,51,0,3.0,0.0,9.0,1.0,...,14.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,2016,GO,5208707,Grupo 1,452,33,14.0,3.0,100.0,0.0,...,16.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,3.0
4,2016,MA,2111300,Grupo 1,498,23,12.0,1.0,27.0,0.0,...,4.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,2021,AC,1200401,Grupo 3,92,4,1.0,0.0,6.0,NaN,...,6.0,NaN,NaN,64.0,200.0,44.0,NaN,NaN,NaN,NaN
158,2021,AM,1302603,Grupo 3,1060,44,12.0,4.0,69.0,NaN,...,5.0,56.0,193.0,249.0,1454.0,191.0,NaN,NaN,NaN,NaN
159,2021,AP,1600303,Grupo 3,184,18,9.0,0.0,119.0,NaN,...,36.0,NaN,NaN,NaN,520.0,156.0,NaN,NaN,NaN,NaN
160,2021,RO,1100205,Grupo 3,161,5,6.0,0.0,6.0,NaN,...,3.0,111.0,286.0,397.0,416.0,109.0,NaN,NaN,NaN,NaN
161,2021,RR,1400100,Grupo 3,128,9,6.0,0.0,9.0,NaN,...,5.0,NaN,NaN,32.0,285.0,185.0,NaN,NaN,NaN,NaN

columns
Index(['ano', 'sigla_uf', 'id_municipio', 'grupo',
       'quantidade_homicidio_doloso', 'quantidade_latrocinio',
       'quantidade_lesao_corporal_morte',
       'quantidade_mortes_policiais_confronto',
       'quantidade_mortes_intervencao_policial',
       'quantidade_mortes_intervencao_policial_civil_em_servico',
       'quantidade_mortes_intervencao_policial_militar_em_servico',
       'quantidade_mortes_intervencao_policial_civil_fora_de_servico',
       'quantidade_mortes_intervencao_policial_militar_fora_de_servico',
       'quantidade_mortes_violentas_intencionais', 'quantidade_feminicidio',
       'quantidade_lesao_corporal_dolosa_violencia_domestica',
       'quantidade_estupro', 'quantidade_roubo_veiculos',
       'quantidade_furto_veiculos', 'quantidade_roubo_furto_veiculos',
       'proporcao_mortes_intenvencao_policial_x_mortes_violentas_intencionais',
       'quantidade_posse_ilegal_arma_de_fogo',
       'quantidade_porte_ilegal_arma_de_fogo',
       'quantidade_posse_ilegal_porte_ilegal_arma_de_fogo',
       'quantidade_trafico_entorpecente', 'quantidade_posse_uso_entorpecente',
       'quantidade_morte_policiais_civis_confronto_em_servico',
       'quantidade_morte_policiais_militares_confronto_em_servico',
       'quantidade_morte_policiais_civis_fora_de_servico',
       'quantidade_morte_policiais_militares_fora_de_servico'],
      dtype='object')

In [25]:
df_mortes_interv_policiais

,ano,sigla_uf,id_municipio,grupo,quantidade_mortes_intervencao_policial,quantidade_mortes_intervencao_policial_civil_em_servico,quantidade_mortes_intervencao_policial_militar_em_servico,quantidade_mortes_intervencao_policial_civil_fora_de_servico,quantidade_mortes_intervencao_policial_militar_fora_de_servico
0,2016,AL,2704302,Grupo 1,59.0,0.0,57.0,0.0,2.0
1,2016,CE,2304400,Grupo 1,39.0,1.0,23.0,0.0,7.0
2,2016,ES,3205309,Grupo 1,9.0,1.0,6.0,0.0,2.0
3,2016,GO,5208707,Grupo 1,100.0,0.0,76.0,0.0,24.0
4,2016,MA,2111300,Grupo 1,27.0,0.0,27.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
157,2021,AC,1200401,Grupo 3,6.0,NaN,NaN,NaN,NaN
158,2021,AM,1302603,Grupo 3,69.0,NaN,NaN,NaN,NaN
159,2021,AP,1600303,Grupo 3,119.0,NaN,NaN,NaN,NaN
160,2021,RO,1100205,Grupo 3,6.0,NaN,NaN,NaN,NaN
161,2021,RR,1400100,Grupo 3,9.0,NaN,NaN,NaN,NaN

In [7]:
df_municipios.head(5)

,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,...,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf,nome_uf,nome_regiao,amazonia_legal,centroide
0,1100338,110033,434,47,44516,Nova Mamoré,0,1100106,11004,Madeira-Mamoré,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-64.6295025002404 -10.3822863210755)
1,1100205,110020,35,3,30719,Porto Velho,1,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-64.3041357999869 -9.15394033687075)
2,1101104,110110,493,683,46851,Itapuã do Oeste,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-63.044960463046 -9.17019402601564)
3,1100809,110080,477,681,46961,Candeias do Jamari,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-63.3254198532114 -8.88702392955617)
4,1100940,110094,680,8,56652,Cujubim,0,1100023,11001,Vale do Jamari,...,Madeira-Guaporé,None,None,69,11,RO,Rondônia,Norte,1,POINT(-62.5652673033848 -9.1709863446154)

In [12]:
# juntando com a tabela de informações de município
df_municipios_join = df_municipios[['id_municipio', 'nome']]
df_municipios_join.head(5)

   id_municipio                nome
0       1100338         Nova Mamoré
1       1100205         Porto Velho
2       1101104     Itapuã do Oeste
3       1100809  Candeias do Jamari
4       1100940             Cujubim

In [24]:
# Dropping columns
df_final = df_municipios_join.merge(df_mortes_interv_policiais, on='id_municipio', how='inner', suffixes=("_left", '_right'))
df_final.head(5)

df_final = df_final.drop(columns=['id_municipio'])

# renaming columns
rename_dict = {
    'quantidade_mortes_intervencao_policial': 'qtd_interv_pol',
    'quantidade_mortes_intervencao_policial_civil_em_servico': 'qtd_pol_civ_serv',
    'quantidade_mortes_intervencao_policial_militar_em_servico': 'qtd_pol_mil_ser',
    'quantidade_mortes_intervencao_policial_civil_fora_de_servico': 'qtd_pol_civ_fora',
    'quantidade_mortes_intervencao_policial_militar_fora_de_servico': 'qtd_pol_mil_fora',
    'nome': 'municipio',
}

df_final = df_final.rename(columns=rename_dict)

# Adding states
estados_para_regiao = {
    # Região Norte
    'AC': 'Norte',
    'AP': 'Norte',
    'AM': 'Norte',
    'PA': 'Norte',
    'RO': 'Norte',
    'RR': 'Norte',
    'TO': 'Norte',
    
    # Região Nordeste
    'AL': 'Nordeste',
    'BA': 'Nordeste',
    'CE': 'Nordeste',
    'MA': 'Nordeste',
    'PB': 'Nordeste',
    'PE': 'Nordeste',
    'PI': 'Nordeste',
    'RN': 'Nordeste',
    'SE': 'Nordeste',
    
    # Região Centro-Oeste
    'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste',
    'MT': 'Centro-Oeste',
    'MS': 'Centro-Oeste',
    
    # Região Sudeste
    'ES': 'Sudeste',
    'MG': 'Sudeste',
    'RJ': 'Sudeste',
    'SP': 'Sudeste',
    
    # Região Sul
    'PR': 'Sul',
    'RS': 'Sul',
    'SC': 'Sul'
}

df_final['regiao'] = df_final['sigla_uf'].map(estados_para_regiao)

df_final

,municipio,ano,sigla_uf,grupo,qtd_interv_pol,qtd_pol_civ_serv,qtd_pol_mil_ser,qtd_pol_civ_fora,qtd_pol_mil_fora,regiao
0,Porto Velho,2016,RO,Grupo 3,6.0,0.0,3.0,0.0,3.0,Norte
1,Porto Velho,2017,RO,Grupo 3,4.0,NaN,3.0,0.0,1.0,Norte
2,Porto Velho,2018,RO,NaN,2.0,NaN,NaN,NaN,NaN,Norte
3,Porto Velho,2019,RO,NaN,7.0,NaN,NaN,NaN,NaN,Norte
4,Porto Velho,2020,RO,Grupo 3,3.0,NaN,NaN,NaN,NaN,Norte
...,...,...,...,...,...,...,...,...,...,...
157,Brasília,2017,DF,Grupo 2,7.0,0.0,2.0,0.0,5.0,Centro-Oeste
158,Brasília,2018,DF,NaN,5.0,NaN,NaN,NaN,NaN,Centro-Oeste
159,Brasília,2019,DF,NaN,8.0,NaN,NaN,NaN,NaN,Centro-Oeste
160,Brasília,2020,DF,Grupo 1,11.0,NaN,NaN,NaN,NaN,Centro-Oeste
161,Brasília,2021,DF,Grupo 1,8.0,NaN,NaN,NaN,NaN,Centro-Oeste

### Dados
- 27 municípios
- 6 anos

Algmumas visualizações:
- Mortes ao longo dos anos
  - Dividindo por policial civil e militar

Black hat:
- Selecionar apenas as cidades onde houve uma diminuição das mortes, fazendo uma agregação que favoreça essa diminuição

White hat:
- Juntar os dados para demonstrar que a maioria das mortes são de pessoas pretas

In [35]:
df_aggregated = df_final.groupby(['ano', 'regiao'], as_index=False)['qtd_interv_pol'].sum()
df_aggregated

     ano        regiao  qtd_interv_pol
0   2016  Centro-Oeste           121.0
1   2016      Nordeste           311.0
2   2016         Norte           154.0
3   2016       Sudeste           966.0
4   2016           Sul           125.0
5   2017  Centro-Oeste           147.0
6   2017      Nordeste           363.0
7   2017         Norte           170.0
8   2017       Sudeste          1016.0
9   2017           Sul           125.0
10  2018  Centro-Oeste            38.0
11  2018      Nordeste           308.0
12  2018         Norte           213.0
13  2018       Sudeste           992.0
14  2018           Sul           136.0
15  2019  Centro-Oeste           173.0
16  2019      Nordeste           416.0
17  2019         Norte           307.0
18  2019       Sudeste          1141.0
19  2019           Sul           110.0
20  2020  Centro-Oeste           180.0
21  2020      Nordeste           572.0
22  2020         Norte           274.0
23  2020       Sudeste           839.0
24  2020           Sul           118.0
25  2021  Centro-Oeste           112.0
26  2021      Nordeste           494.0
27  2021         Norte           299.0
28  2021       Sudeste           763.0
29  2021           Sul           148.0